# Generated by Django 5.2 on 2025-04-11 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='allow_comment',
            field=models.BooleanField(default=True, verbose_name='允许评论'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('experience', '环保经验'), ('news', '环保新闻'), ('discussion', '话题讨论')], default='experience', max_length=20, verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/', verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='是否为草稿'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comment'),
        ),
    ]
